#ifndef _VEHICLE_COMMAND_H
#define _VEHICLE_COMMAND_H

typedef enum
{
    COMMAND_MOVE_FACE_FORWARD,
    COMMAND_MOVE_FACE_BACKWARD,
    COMMAND_MOVE_SIDE_RIGHT,
    COMMAND_MOVE_SIDE_LEFT,
    COMMAND_MOVE_DIAG_FORWARD_RIGHT,
    COMMAND_MOVE_DIAG_FORWARD_LEFT,
    COMMAND_MOVE_DIAG_BACKWARD_RIGHT,
    COMMAND_MOVE_DIAG_BACKWARD_LEFT,
    COMMAND_ROTATE_SIDE_RIGHT_FORWARD,
    COMMAND_ROTATE_SIDE_LEFT_FORWARD,
    COMMAND_ROTATE_SIDE_RIGHT_BACKWARD,
    COMMAND_ROTATE_SIDE_LEFT_BACKWARD,
    COMMAND_ROTATE_RIGHT,
    COMMAND_ROTATE_LEFT,
    COMMAND_ROTATE_FACE_FRONT_RIGHT,
    COMMAND_ROTATE_FACE_FRONT_LEFT,
    COMMAND_ROTATE_FACE_REAR_RIGHT,
    COMMAND_ROTATE_FACE_REAR_LEFT,
    COMMAND_SOFT_STOP,
    COMMAND_HARD_STOP,
} command_t;

void
command_init(void);

command_t
command_receive(void);

#endif