#ifndef _CONTROL_H
#define _CONTROL_H

typedef enum
{
    CTRL_MOVE_FACE_FORWARD,
    CTRL_MOVE_FACE_BACKWARD,
    CTRL_MOVE_SIDE_RIGHT,
    CTRL_MOVE_SIDE_LEFT,
    CTRL_MOVE_DIAG_FORWARD_RIGHT,
    CTRL_MOVE_DIAG_FORWARD_LEFT,
    CTRL_MOVE_DIAG_BACKWARD_RIGHT,
    CTRL_MOVE_DIAG_BACKWARD_LEFT,
    CTRL_ROTATE_SIDE_RIGHT_FORWARD,
    CTRL_ROTATE_SIDE_LEFT_FORWARD,
    CTRL_ROTATE_SIDE_RIGHT_BACKWARD,
    CTRL_ROTATE_SIDE_LEFT_BACKWARD,
    CTRL_ROTATE_RIGHT,
    CTRL_ROTATE_LEFT,
    CTRL_ROTATE_FACE_FRONT_RIGHT,
    CTRL_ROTATE_FACE_FRONT_LEFT,
    CTRL_ROTATE_FACE_REAR_RIGHT,
    CTRL_ROTATE_FACE_REAR_LEFT,
    CTRL_SOFT_STOP,
    CTRL_HARD_STOP,
} control_command_t;

void
control_init(void);

control_command_t
control_read(void);

#endif
