#ifndef _COMM_H
#define _COMM_H

typedef enum
{
    COMM_MOVE_FACE_FORWARD,
    COMM_MOVE_FACE_BACKWARD,
    COMM_MOVE_SIDE_RIGHT,
    COMM_MOVE_SIDE_LEFT,
    COMM_MOVE_DIAG_FORWARD_RIGHT,
    COMM_MOVE_DIAG_FORWARD_LEFT,
    COMM_MOVE_DIAG_BACKWARD_RIGHT,
    COMM_MOVE_DIAG_BACKWARD_LEFT,
    COMM_ROTATE_SIDE_RIGHT_FORWARD,
    COMM_ROTATE_SIDE_LEFT_FORWARD,
    COMM_ROTATE_SIDE_RIGHT_BACKWARD,
    COMM_ROTATE_SIDE_LEFT_BACKWARD,
    COMM_ROTATE_RIGHT,
    COMM_ROTATE_LEFT,
    COMM_ROTATE_FACE_FRONT_RIGHT,
    COMM_ROTATE_FACE_FRONT_LEFT,
    COMM_ROTATE_FACE_REAR_RIGHT,
    COMM_ROTATE_FACE_REAR_LEFT,
    COMM_SOFT_STOP,
    COMM_HARD_STOP,
} comm_command_t;

void
comm_init(void);

comm_command_t
comm_read(void);

#endif
